"""Build and source contracts that make device evidence reproducible."""

from __future__ import annotations

import hashlib
import os
import re
import stat
import shutil
import subprocess
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence


class ContractError(RuntimeError):
    pass


@dataclass(frozen=True)
class ApkContract:
    application_id: str
    launcher_component: str
    snapshot_component: str


DEBUG_SOURCE_SCOPES = (
    "app/src/main",
    "app/src/debug",
    "app/build.gradle.kts",
    "app/compose_stability.conf",
    "build.gradle.kts",
    "settings.gradle.kts",
    "gradle.properties",
    "gradle/libs.versions.toml",
    "gradle/wrapper/gradle-wrapper.properties",
)
DEBUG_PROVENANCE_NAMESPACE = "assets/telecam-debug-provenance/"
DEBUG_PROVENANCE_MEMBER = DEBUG_PROVENANCE_NAMESPACE + "source.manifest"
IMMUTABLE_DEBUG_SOURCE_OWNER = "immutable-debug-worktree-v1"
MUTABLE_DEBUG_SOURCE_OWNER = "mutable-development-worktree"
_MAX_DEBUG_SOURCE_FILE_BYTES = 64 * 1024 * 1024
_MAX_DEBUG_SOURCE_TOTAL_BYTES = 512 * 1024 * 1024
_MAX_DEBUG_SOURCE_FILES = 16_384
_DEBUG_READ_CHUNK_BYTES = 1024 * 1024


@dataclass(frozen=True)
class SourceManifestEntry:
    path: str
    bytes: int
    sha256: str


@dataclass(frozen=True)
class DebugSourceIdentity:
    commit: str
    dirty: bool
    content_sha256: str
    files: tuple[SourceManifestEntry, ...]
    source_owner: str = MUTABLE_DEBUG_SOURCE_OWNER

    @property
    def identity(self) -> str:
        state = "dirty" if self.dirty else "clean"
        return (
            f"git:{self.commit}/content-sha256:{self.content_sha256}/"
            f"{state}/source-owner:{self.source_owner}"
        )

    def as_attestation(self) -> dict[str, object]:
        return {
            "identity": self.identity,
            "commit": self.commit,
            "dirty": self.dirty,
            "source_owner": self.source_owner,
            "content_manifest_sha256": self.content_sha256,
            "file_count": len(self.files),
            "files": [
                {"path": entry.path, "bytes": entry.bytes, "sha256": entry.sha256}
                for entry in self.files
            ],
        }


def _canonical_source_entries(entries: Sequence[SourceManifestEntry]) -> bytes:
    return "".join(
        f"{entry.sha256}  {entry.bytes}  {entry.path}\n" for entry in entries
    ).encode()


def _source_content_sha256(entries: Sequence[SourceManifestEntry]) -> str:
    return hashlib.sha256(_canonical_source_entries(entries)).hexdigest()


def render_debug_source_manifest(identity: DebugSourceIdentity) -> bytes:
    """Render the strict line format generated by the Android debug build."""
    header = (
        "schema=2\n"
        f"source_owner={identity.source_owner}\n"
        f"commit={identity.commit}\n"
        f"dirty={'true' if identity.dirty else 'false'}\n"
        f"content_sha256={identity.content_sha256}\n"
        f"file_count={len(identity.files)}\n"
    ).encode()
    return header + _canonical_source_entries(identity.files)


def parse_debug_source_manifest(payload: bytes) -> DebugSourceIdentity:
    """Parse packaged provenance strictly; ambiguity must fail device evidence closed."""
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ContractError(f"debug source manifest is not UTF-8: {error}") from error
    if not text.endswith("\n") or "\r" in text or "\x00" in text:
        raise ContractError("debug source manifest must be LF-terminated UTF-8 text")
    lines = text.splitlines()
    if len(lines) < 7 or lines[0] != "schema=2":
        raise ContractError("debug source manifest schema/header is missing or unsupported")

    def value(index: int, key: str) -> str:
        prefix = key + "="
        if not lines[index].startswith(prefix):
            raise ContractError(f"debug source manifest expected {key!r} at line {index + 1}")
        return lines[index][len(prefix):]

    source_owner = value(1, "source_owner")
    commit = value(2, "commit")
    dirty_text = value(3, "dirty")
    content_sha256 = value(4, "content_sha256")
    count_text = value(5, "file_count")
    if source_owner not in {IMMUTABLE_DEBUG_SOURCE_OWNER, MUTABLE_DEBUG_SOURCE_OWNER}:
        raise ContractError("debug source manifest source_owner is unsupported")
    if re.fullmatch(r"[0-9a-f]{40}", commit) is None:
        raise ContractError("debug source manifest commit is not a full lowercase Git object id")
    if dirty_text not in {"true", "false"}:
        raise ContractError("debug source manifest dirty value must be true or false")
    if re.fullmatch(r"[0-9a-f]{64}", content_sha256) is None:
        raise ContractError("debug source manifest content SHA-256 is malformed")
    if re.fullmatch(r"0|[1-9][0-9]*", count_text) is None:
        raise ContractError("debug source manifest file count is malformed")

    entries: list[SourceManifestEntry] = []
    for line in lines[6:]:
        match = re.fullmatch(r"([0-9a-f]{64})  (0|[1-9][0-9]*)  (.+)", line)
        if match is None:
            raise ContractError("debug source manifest contains a malformed file row")
        path = match.group(3)
        path_parts = Path(path).parts
        if (
            path.startswith("/")
            or "\\" in path
            or not path_parts
            or any(part in {"", ".", ".."} for part in path_parts)
        ):
            raise ContractError(f"debug source manifest contains an unsafe path: {path!r}")
        entries.append(SourceManifestEntry(path, int(match.group(2)), match.group(1)))
    if len(entries) != int(count_text) or not entries:
        raise ContractError(
            f"debug source manifest file count mismatch: declared={count_text} actual={len(entries)}"
        )
    paths = [entry.path for entry in entries]
    if paths != sorted(paths) or len(paths) != len(set(paths)):
        raise ContractError("debug source manifest paths must be unique and sorted")
    if _source_content_sha256(entries) != content_sha256:
        raise ContractError("debug source manifest content SHA-256 does not match its file rows")
    return DebugSourceIdentity(
        commit,
        dirty_text == "true",
        content_sha256,
        tuple(entries),
        source_owner,
    )


def inspect_apk_source_identity(apk: Path) -> DebugSourceIdentity:
    """Read the one debug provenance member from the exact APK ZIP bytes."""
    if not apk.is_file():
        raise ContractError(f"APK does not exist: {apk}")
    try:
        with zipfile.ZipFile(apk) as archive:
            members = [
                info for info in archive.infolist()
                if info.filename.startswith(DEBUG_PROVENANCE_NAMESPACE)
                and not info.is_dir()
            ]
            if [info.filename for info in members] != [DEBUG_PROVENANCE_MEMBER]:
                raise ContractError(
                    "debug APK must contain exactly one source provenance member; "
                    f"found {[info.filename for info in members]}"
                )
            return parse_debug_source_manifest(archive.read(members[0]))
    except (OSError, zipfile.BadZipFile, RuntimeError) as error:
        if isinstance(error, ContractError):
            raise
        raise ContractError(f"could not read debug APK source provenance: {error}") from error


def _debug_open_flags(*, directory: bool = False) -> int:
    no_follow = getattr(os, "O_NOFOLLOW", None)
    if no_follow is None:
        raise ContractError("this host cannot enforce no-follow debug-source reads")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | no_follow
    if directory:
        flags |= getattr(os, "O_DIRECTORY", 0)
    return flags


def _same_file_identity(left: os.stat_result, right: os.stat_result) -> bool:
    return (left.st_dev, left.st_ino, stat.S_IFMT(left.st_mode)) == (
        right.st_dev,
        right.st_ino,
        stat.S_IFMT(right.st_mode),
    )


def _debug_entry_stat(parent_fd: int, name: str) -> os.stat_result:
    return os.stat(name, dir_fd=parent_fd, follow_symlinks=False)


def _open_debug_directory(parent_fd: int | None, name: str, relative: Path) -> int:
    try:
        descriptor = os.open(name, _debug_open_flags(directory=True), dir_fd=parent_fd)
    except OSError as error:
        raise ContractError(
            f"debug source directory must be stable and non-symlink: {relative.as_posix()}"
        ) from error
    opened = os.fstat(descriptor)
    if not stat.S_ISDIR(opened.st_mode):
        os.close(descriptor)
        raise ContractError(f"debug source must be a directory: {relative.as_posix()}")
    return descriptor


def _hash_debug_file(
    parent_fd: int,
    name: str,
    relative: Path,
    expected: os.stat_result,
) -> SourceManifestEntry:
    try:
        descriptor = os.open(name, _debug_open_flags(), dir_fd=parent_fd)
    except OSError as error:
        raise ContractError(
            f"debug source input must be a stable non-symlink file: {relative.as_posix()}"
        ) from error
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode) or not _same_file_identity(expected, before):
            raise ContractError(f"debug source input changed before open: {relative.as_posix()}")
        if before.st_size < 0 or before.st_size > _MAX_DEBUG_SOURCE_FILE_BYTES:
            raise ContractError(
                f"debug source input exceeds {_MAX_DEBUG_SOURCE_FILE_BYTES} bytes: "
                f"{relative.as_posix()}"
            )
        digest = hashlib.sha256()
        total = 0
        while True:
            chunk = os.read(
                descriptor,
                min(_DEBUG_READ_CHUNK_BYTES, _MAX_DEBUG_SOURCE_FILE_BYTES + 1 - total),
            )
            if not chunk:
                break
            digest.update(chunk)
            total += len(chunk)
            if total > _MAX_DEBUG_SOURCE_FILE_BYTES:
                raise ContractError(
                    f"debug source input grew beyond {_MAX_DEBUG_SOURCE_FILE_BYTES} bytes: "
                    f"{relative.as_posix()}"
                )
        after = os.fstat(descriptor)
        try:
            current = _debug_entry_stat(parent_fd, name)
        except OSError as error:
            raise ContractError(
                f"debug source input disappeared while reading: {relative.as_posix()}"
            ) from error
        if (
            not _same_file_identity(before, after)
            or not _same_file_identity(after, current)
            or before.st_size != after.st_size
            or before.st_mtime_ns != after.st_mtime_ns
            or before.st_ctime_ns != after.st_ctime_ns
            or total != after.st_size
        ):
            raise ContractError(f"debug source input changed while reading: {relative.as_posix()}")
        return SourceManifestEntry(relative.as_posix(), total, digest.hexdigest())
    finally:
        os.close(descriptor)


def _frozen_debug_source_entries(
    repo_root: Path,
    scopes: Sequence[str],
    *,
    expected_root_identity: os.stat_result | None = None,
) -> tuple[SourceManifestEntry, ...]:
    """Hash one exact bounded source set through pinned no-follow directory descriptors."""
    root = Path(os.path.abspath(repo_root))
    try:
        expected_root = os.stat(root, follow_symlinks=False)
    except OSError as error:
        raise ContractError(f"debug source root is unavailable: {root}") from error
    if not stat.S_ISDIR(expected_root.st_mode):
        raise ContractError(f"debug source root must be a non-symlink directory: {root}")
    if expected_root_identity is not None and not _same_file_identity(
        expected_root_identity,
        expected_root,
    ):
        raise ContractError(f"debug source root changed before identity freeze: {root}")
    root_fd = _open_debug_directory(None, str(root), Path("."))
    root_identity = os.fstat(root_fd)
    if not _same_file_identity(expected_root, root_identity):
        os.close(root_fd)
        raise ContractError(f"debug source root changed before open: {root}")

    entries: dict[str, SourceManifestEntry] = {}
    total_bytes = 0

    def add_file(parent_fd: int, name: str, relative: Path, observed: os.stat_result) -> None:
        nonlocal total_bytes
        entry = _hash_debug_file(parent_fd, name, relative, observed)
        if entry.path in entries:
            raise ContractError(f"debug source scopes overlap at: {entry.path}")
        entries[entry.path] = entry
        total_bytes += entry.bytes
        if len(entries) > _MAX_DEBUG_SOURCE_FILES or total_bytes > _MAX_DEBUG_SOURCE_TOTAL_BYTES:
            raise ContractError("debug source tree exceeds its bounded identity budget")

    def walk(directory_fd: int, relative_directory: Path) -> None:
        with os.scandir(directory_fd) as iterator:
            initial_names = sorted(entry.name for entry in iterator)
        for name in initial_names:
            relative = relative_directory / name
            try:
                observed = _debug_entry_stat(directory_fd, name)
            except OSError as error:
                raise ContractError(
                    f"debug source member disappeared during enumeration: {relative.as_posix()}"
                ) from error
            if stat.S_ISLNK(observed.st_mode):
                raise ContractError(f"debug source input must not be a symlink: {relative.as_posix()}")
            if stat.S_ISDIR(observed.st_mode):
                child_fd = _open_debug_directory(directory_fd, name, relative)
                opened = os.fstat(child_fd)
                try:
                    if not _same_file_identity(observed, opened):
                        raise ContractError(
                            f"debug source directory changed before open: {relative.as_posix()}"
                        )
                    walk(child_fd, relative)
                    current = _debug_entry_stat(directory_fd, name)
                    if not _same_file_identity(opened, current):
                        raise ContractError(
                            f"debug source directory changed while reading: {relative.as_posix()}"
                        )
                finally:
                    os.close(child_fd)
                continue
            if not stat.S_ISREG(observed.st_mode):
                raise ContractError(f"debug source input must be a regular file: {relative.as_posix()}")
            add_file(directory_fd, name, relative, observed)
        with os.scandir(directory_fd) as iterator:
            final_names = sorted(entry.name for entry in iterator)
        if final_names != initial_names:
            raise ContractError(
                "debug source member set changed while reading under "
                f"{relative_directory.as_posix() or '.'}"
            )

    try:
        for scope in scopes:
            scoped = Path(scope)
            if (
                scoped.is_absolute()
                or "\\" in scope
                or not scoped.parts
                or any(part in {"", ".", ".."} for part in scoped.parts)
            ):
                raise ContractError(f"debug source scope is unsafe: {scope!r}")
            directory_fds = [os.dup(root_fd)]
            try:
                for index, part in enumerate(scoped.parts[:-1]):
                    parent_fd = directory_fds[-1]
                    relative = Path(*scoped.parts[: index + 1])
                    observed = _debug_entry_stat(parent_fd, part)
                    if not stat.S_ISDIR(observed.st_mode):
                        raise ContractError(
                            f"debug source scope parent is not a directory: {relative.as_posix()}"
                        )
                    child_fd = _open_debug_directory(parent_fd, part, relative)
                    opened = os.fstat(child_fd)
                    if not _same_file_identity(observed, opened):
                        os.close(child_fd)
                        raise ContractError(
                            f"debug source scope parent changed before open: {relative.as_posix()}"
                        )
                    directory_fds.append(child_fd)
                parent_fd = directory_fds[-1]
                leaf = scoped.parts[-1]
                try:
                    observed = _debug_entry_stat(parent_fd, leaf)
                except OSError as error:
                    raise ContractError(f"debug source scope is missing: {scope}") from error
                if stat.S_ISLNK(observed.st_mode):
                    raise ContractError(f"debug source scope must not be a symlink: {scope}")
                if stat.S_ISDIR(observed.st_mode):
                    child_fd = _open_debug_directory(parent_fd, leaf, scoped)
                    opened = os.fstat(child_fd)
                    try:
                        if not _same_file_identity(observed, opened):
                            raise ContractError(
                                f"debug source scope changed before open: {scope}"
                            )
                        walk(child_fd, scoped)
                        current = _debug_entry_stat(parent_fd, leaf)
                        if not _same_file_identity(opened, current):
                            raise ContractError(
                                f"debug source scope changed while reading: {scope}"
                            )
                    finally:
                        os.close(child_fd)
                elif stat.S_ISREG(observed.st_mode):
                    add_file(parent_fd, leaf, scoped, observed)
                else:
                    raise ContractError(f"debug source scope must be a regular file or directory: {scope}")
                for index in range(len(directory_fds) - 1, 0, -1):
                    parent = directory_fds[index - 1]
                    opened = os.fstat(directory_fds[index])
                    component = scoped.parts[index - 1]
                    current = _debug_entry_stat(parent, component)
                    if not _same_file_identity(opened, current):
                        relative = Path(*scoped.parts[:index])
                        raise ContractError(
                            f"debug source scope parent changed while reading: {relative.as_posix()}"
                        )
            finally:
                for descriptor in reversed(directory_fds):
                    os.close(descriptor)
        final_root = os.stat(root, follow_symlinks=False)
        if not _same_file_identity(root_identity, final_root):
            raise ContractError("debug source root changed while reading")
    finally:
        os.close(root_fd)
    if not entries:
        raise ContractError("no current debug source inputs were found")
    return tuple(entries[path] for path in sorted(entries))


def current_debug_source_identity(
    repo_root: Path,
    *,
    scopes: Sequence[str] = DEBUG_SOURCE_SCOPES,
) -> DebugSourceIdentity:
    """Hash the current packageable debug inputs using the build task's canonical format."""
    root = Path(os.path.abspath(repo_root))
    try:
        root_identity = os.stat(root, follow_symlinks=False)
    except OSError as error:
        raise ContractError(f"debug source root is unavailable: {root}") from error
    entries = _frozen_debug_source_entries(
        root,
        scopes,
        expected_root_identity=root_identity,
    )

    def git(*arguments: str) -> bytes:
        result = subprocess.run(
            ["git", *arguments],
            cwd=root,
            capture_output=True,
            timeout=30,
        )
        if result.returncode != 0:
            raise ContractError(
                f"git {' '.join(arguments)} failed: {(result.stderr or result.stdout)[:300]!r}"
            )
        return result.stdout

    commit = git("rev-parse", "HEAD").decode("ascii").strip()
    if re.fullmatch(r"[0-9a-f]{40}", commit) is None:
        raise ContractError("current Git commit is not a full lowercase object id")
    changed = git(
        "status", "--porcelain=v1", "-z", "--untracked-files=all",
        "--ignore-submodules=none", "--", *scopes,
    )
    ignored = git(
        "ls-files", "-z", "--others", "--ignored", "--exclude-standard", "--", *scopes,
    )
    if _frozen_debug_source_entries(
        root,
        scopes,
        expected_root_identity=root_identity,
    ) != entries:
        raise ContractError("debug source identity changed while Git state was inspected")
    return DebugSourceIdentity(
        commit,
        bool(changed or ignored),
        _source_content_sha256(entries),
        entries,
    )


def require_apk_source_match(apk: Path, repo_root: Path) -> DebugSourceIdentity:
    """Fail unless current packageable inputs exactly match provenance inside ``apk``."""
    packaged = inspect_apk_source_identity(apk)
    if packaged.source_owner != IMMUTABLE_DEBUG_SOURCE_OWNER:
        raise ContractError(
            "debug APK is not evidence-grade: source_owner=" + packaged.source_owner
        )
    current = current_debug_source_identity(repo_root)
    differences = []
    if packaged.commit != current.commit:
        differences.append(f"commit {packaged.commit} != {current.commit}")
    if packaged.dirty != current.dirty:
        differences.append(f"dirty {packaged.dirty} != {current.dirty}")
    if packaged.content_sha256 != current.content_sha256 or packaged.files != current.files:
        differences.append(
            f"content {packaged.content_sha256} != {current.content_sha256}"
        )
    if differences:
        raise ContractError("stale/mismatched debug APK source: " + "; ".join(differences))
    return packaged


def _version_key(path: Path) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r"\d+", path.parent.name))


def find_build_tool(name: str) -> str:
    candidates: list[Path] = []
    for root_text in (
        os.environ.get("ANDROID_SDK_ROOT"),
        os.environ.get("ANDROID_HOME"),
        str(Path.home() / "Library/Android/sdk"),
    ):
        if root_text:
            candidates.extend(Path(root_text).glob(f"build-tools/*/{name}"))
    if candidates:
        return str(max(candidates, key=_version_key))
    resolved = shutil.which(name)
    if resolved is None:
        raise ContractError(f"Android build tool {name!r} was not found")
    return resolved


def _run_text(command: Sequence[str]) -> str:
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise ContractError(
            f"{' '.join(command[:3])} failed: {(result.stderr or result.stdout)[:300]}"
        )
    return result.stdout


def normalize_component(application_id: str, activity_name: str) -> str:
    if activity_name.startswith("."):
        activity_name = application_id + activity_name
    elif "." not in activity_name:
        activity_name = f"{application_id}.{activity_name}"
    return f"{application_id}/{activity_name}"


def parse_apk_contract(badging: str, xmltree: str) -> ApkContract:
    package_match = re.search(r"^package: name='([^']+)'", badging, re.MULTILINE)
    launcher_match = re.search(r"^launchable-activity: name='([^']+)'", badging, re.MULTILINE)
    if package_match is None or launcher_match is None:
        raise ContractError("APK badging omitted package or launchable activity")
    application_id = package_match.group(1)
    activities = re.findall(
        r'android:name\([^)]*\)="([^"]+)"(?: \(Raw: "[^"]+"\))?',
        xmltree,
    )
    snapshots = [name for name in activities if name.endswith(".ui.UiSnapshotActivity")]
    if len(snapshots) != 1:
        raise ContractError(
            f"debug APK must expose exactly one UiSnapshotActivity; found {snapshots}"
        )
    return ApkContract(
        application_id=application_id,
        launcher_component=normalize_component(application_id, launcher_match.group(1)),
        snapshot_component=normalize_component(application_id, snapshots[0]),
    )


def inspect_apk_contract(
    apk: Path,
    *,
    run_text: Callable[[Sequence[str]], str] = _run_text,
    aapt: str | None = None,
    aapt2: str | None = None,
) -> ApkContract:
    """Read identity from the same APK bytes whose SHA is attested."""
    if not apk.is_file():
        raise ContractError(f"APK does not exist: {apk}")
    badging = run_text([aapt or find_build_tool("aapt"), "dump", "badging", str(apk)])
    xmltree = run_text(
        [
            aapt2 or find_build_tool("aapt2"),
            "dump",
            "xmltree",
            "--file",
            "AndroidManifest.xml",
            str(apk),
        ]
    )
    return parse_apk_contract(badging, xmltree)


def production_capture_subdir(repo_root: Path) -> str:
    source = (
        repo_root
        / "app/src/main/kotlin/me/hletrd/telecampro/storage/MediaStoreWriter.kt"
    ).read_text(encoding="utf-8")
    matches = re.findall(r'^\s*const val CAPTURE_SUBDIR\s*=\s*"([^"]+)"', source, re.MULTILINE)
    if len(matches) != 1:
        raise ContractError(f"expected one production CAPTURE_SUBDIR, found {matches}")
    return matches[0]


def harness_source_manifest(harness_root: Path) -> list[dict[str, object]]:
    """Hash every versionable harness input, excluding only generated artifacts/caches."""
    entries: list[dict[str, object]] = []
    for path in sorted(harness_root.rglob("*")):
        relative = path.relative_to(harness_root)
        if any(part in {"reports", "__pycache__", ".pytest_cache"} for part in relative.parts):
            continue
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            raise ContractError(f"harness source must not be a symlink: {relative.as_posix()}")
        if stat.S_ISDIR(mode):
            continue
        if not stat.S_ISREG(mode):
            raise ContractError(f"harness source must be a regular file: {relative.as_posix()}")
        payload = path.read_bytes()
        entries.append(
            {
                "path": relative.as_posix(),
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
            }
        )
    if not entries:
        raise ContractError(f"no harness sources found under {harness_root}")
    return entries


def source_manifest_sha256(entries: list[dict[str, object]]) -> str:
    canonical = "".join(
        f"{entry['sha256']}  {entry['bytes']}  {entry['path']}\n" for entry in entries
    ).encode()
    return hashlib.sha256(canonical).hexdigest()
