"""Build and source contracts that make device evidence reproducible."""

from __future__ import annotations

import hashlib
import os
import re
import stat
import shutil
import subprocess
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence


class ContractError(RuntimeError):
    pass


@dataclass(frozen=True)
class ApkContract:
    application_id: str
    launcher_component: str
    snapshot_component: str


DEBUG_SOURCE_SCOPES = (
    "app/src/main",
    "app/src/debug",
    "app/build.gradle.kts",
    "app/compose_stability.conf",
    "build.gradle.kts",
    "settings.gradle.kts",
    "gradle.properties",
    "gradle/libs.versions.toml",
    "gradle/wrapper/gradle-wrapper.properties",
)
DEBUG_PROVENANCE_NAMESPACE = "assets/telecam-debug-provenance/"
DEBUG_PROVENANCE_MEMBER = DEBUG_PROVENANCE_NAMESPACE + "source.manifest"


@dataclass(frozen=True)
class SourceManifestEntry:
    path: str
    bytes: int
    sha256: str


@dataclass(frozen=True)
class DebugSourceIdentity:
    commit: str
    dirty: bool
    content_sha256: str
    files: tuple[SourceManifestEntry, ...]

    @property
    def identity(self) -> str:
        state = "dirty" if self.dirty else "clean"
        return f"git:{self.commit}/content-sha256:{self.content_sha256}/{state}"

    def as_attestation(self) -> dict[str, object]:
        return {
            "identity": self.identity,
            "commit": self.commit,
            "dirty": self.dirty,
            "content_manifest_sha256": self.content_sha256,
            "file_count": len(self.files),
            "files": [
                {"path": entry.path, "bytes": entry.bytes, "sha256": entry.sha256}
                for entry in self.files
            ],
        }


def _canonical_source_entries(entries: Sequence[SourceManifestEntry]) -> bytes:
    return "".join(
        f"{entry.sha256}  {entry.bytes}  {entry.path}\n" for entry in entries
    ).encode()


def _source_content_sha256(entries: Sequence[SourceManifestEntry]) -> str:
    return hashlib.sha256(_canonical_source_entries(entries)).hexdigest()


def render_debug_source_manifest(identity: DebugSourceIdentity) -> bytes:
    """Render the strict line format generated by the Android debug build."""
    header = (
        "schema=1\n"
        f"commit={identity.commit}\n"
        f"dirty={'true' if identity.dirty else 'false'}\n"
        f"content_sha256={identity.content_sha256}\n"
        f"file_count={len(identity.files)}\n"
    ).encode()
    return header + _canonical_source_entries(identity.files)


def parse_debug_source_manifest(payload: bytes) -> DebugSourceIdentity:
    """Parse packaged provenance strictly; ambiguity must fail device evidence closed."""
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ContractError(f"debug source manifest is not UTF-8: {error}") from error
    if not text.endswith("\n") or "\r" in text or "\x00" in text:
        raise ContractError("debug source manifest must be LF-terminated UTF-8 text")
    lines = text.splitlines()
    if len(lines) < 6 or lines[0] != "schema=1":
        raise ContractError("debug source manifest schema/header is missing or unsupported")

    def value(index: int, key: str) -> str:
        prefix = key + "="
        if not lines[index].startswith(prefix):
            raise ContractError(f"debug source manifest expected {key!r} at line {index + 1}")
        return lines[index][len(prefix):]

    commit = value(1, "commit")
    dirty_text = value(2, "dirty")
    content_sha256 = value(3, "content_sha256")
    count_text = value(4, "file_count")
    if re.fullmatch(r"[0-9a-f]{40}", commit) is None:
        raise ContractError("debug source manifest commit is not a full lowercase Git object id")
    if dirty_text not in {"true", "false"}:
        raise ContractError("debug source manifest dirty value must be true or false")
    if re.fullmatch(r"[0-9a-f]{64}", content_sha256) is None:
        raise ContractError("debug source manifest content SHA-256 is malformed")
    if re.fullmatch(r"0|[1-9][0-9]*", count_text) is None:
        raise ContractError("debug source manifest file count is malformed")

    entries: list[SourceManifestEntry] = []
    for line in lines[5:]:
        match = re.fullmatch(r"([0-9a-f]{64})  (0|[1-9][0-9]*)  (.+)", line)
        if match is None:
            raise ContractError("debug source manifest contains a malformed file row")
        path = match.group(3)
        path_parts = Path(path).parts
        if (
            path.startswith("/")
            or "\\" in path
            or not path_parts
            or any(part in {"", ".", ".."} for part in path_parts)
        ):
            raise ContractError(f"debug source manifest contains an unsafe path: {path!r}")
        entries.append(SourceManifestEntry(path, int(match.group(2)), match.group(1)))
    if len(entries) != int(count_text) or not entries:
        raise ContractError(
            f"debug source manifest file count mismatch: declared={count_text} actual={len(entries)}"
        )
    paths = [entry.path for entry in entries]
    if paths != sorted(paths) or len(paths) != len(set(paths)):
        raise ContractError("debug source manifest paths must be unique and sorted")
    if _source_content_sha256(entries) != content_sha256:
        raise ContractError("debug source manifest content SHA-256 does not match its file rows")
    return DebugSourceIdentity(commit, dirty_text == "true", content_sha256, tuple(entries))


def inspect_apk_source_identity(apk: Path) -> DebugSourceIdentity:
    """Read the one debug provenance member from the exact APK ZIP bytes."""
    if not apk.is_file():
        raise ContractError(f"APK does not exist: {apk}")
    try:
        with zipfile.ZipFile(apk) as archive:
            members = [
                info for info in archive.infolist()
                if info.filename.startswith(DEBUG_PROVENANCE_NAMESPACE)
                and not info.is_dir()
            ]
            if [info.filename for info in members] != [DEBUG_PROVENANCE_MEMBER]:
                raise ContractError(
                    "debug APK must contain exactly one source provenance member; "
                    f"found {[info.filename for info in members]}"
                )
            return parse_debug_source_manifest(archive.read(members[0]))
    except (OSError, zipfile.BadZipFile, RuntimeError) as error:
        if isinstance(error, ContractError):
            raise
        raise ContractError(f"could not read debug APK source provenance: {error}") from error


def current_debug_source_identity(
    repo_root: Path,
    *,
    scopes: Sequence[str] = DEBUG_SOURCE_SCOPES,
) -> DebugSourceIdentity:
    """Hash the current packageable debug inputs using the build task's canonical format."""
    root = repo_root.resolve()
    files: dict[str, Path] = {}
    for scope in scopes:
        scoped = root / scope
        if scoped.is_symlink():
            raise ContractError(f"debug source scope must not be a symlink: {scope}")
        if scoped.is_dir():
            candidates = scoped.rglob("*")
        elif scoped.is_file():
            candidates = (scoped,)
        else:
            raise ContractError(f"debug source scope is missing: {scope}")
        for candidate in candidates:
            if candidate.is_symlink():
                raise ContractError(
                    f"debug source input must not be a symlink: {candidate.relative_to(root)}"
                )
            if not candidate.is_file():
                continue
            relative = candidate.relative_to(root).as_posix()
            files[relative] = candidate
    entries = tuple(
        SourceManifestEntry(path, file.stat().st_size, hashlib.sha256(file.read_bytes()).hexdigest())
        for path, file in sorted(files.items())
    )
    if not entries:
        raise ContractError("no current debug source inputs were found")

    def git(*arguments: str) -> bytes:
        result = subprocess.run(
            ["git", *arguments],
            cwd=root,
            capture_output=True,
            timeout=30,
        )
        if result.returncode != 0:
            raise ContractError(
                f"git {' '.join(arguments)} failed: {(result.stderr or result.stdout)[:300]!r}"
            )
        return result.stdout

    commit = git("rev-parse", "HEAD").decode("ascii").strip()
    if re.fullmatch(r"[0-9a-f]{40}", commit) is None:
        raise ContractError("current Git commit is not a full lowercase object id")
    changed = git(
        "status", "--porcelain=v1", "-z", "--untracked-files=all",
        "--ignore-submodules=none", "--", *scopes,
    )
    ignored = git(
        "ls-files", "-z", "--others", "--ignored", "--exclude-standard", "--", *scopes,
    )
    return DebugSourceIdentity(
        commit,
        bool(changed or ignored),
        _source_content_sha256(entries),
        entries,
    )


def require_apk_source_match(apk: Path, repo_root: Path) -> DebugSourceIdentity:
    """Fail unless current packageable inputs exactly match provenance inside ``apk``."""
    packaged = inspect_apk_source_identity(apk)
    current = current_debug_source_identity(repo_root)
    differences = []
    if packaged.commit != current.commit:
        differences.append(f"commit {packaged.commit} != {current.commit}")
    if packaged.dirty != current.dirty:
        differences.append(f"dirty {packaged.dirty} != {current.dirty}")
    if packaged.content_sha256 != current.content_sha256 or packaged.files != current.files:
        differences.append(
            f"content {packaged.content_sha256} != {current.content_sha256}"
        )
    if differences:
        raise ContractError("stale/mismatched debug APK source: " + "; ".join(differences))
    return packaged


def _version_key(path: Path) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r"\d+", path.parent.name))


def find_build_tool(name: str) -> str:
    candidates: list[Path] = []
    for root_text in (
        os.environ.get("ANDROID_SDK_ROOT"),
        os.environ.get("ANDROID_HOME"),
        str(Path.home() / "Library/Android/sdk"),
    ):
        if root_text:
            candidates.extend(Path(root_text).glob(f"build-tools/*/{name}"))
    if candidates:
        return str(max(candidates, key=_version_key))
    resolved = shutil.which(name)
    if resolved is None:
        raise ContractError(f"Android build tool {name!r} was not found")
    return resolved


def _run_text(command: Sequence[str]) -> str:
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise ContractError(
            f"{' '.join(command[:3])} failed: {(result.stderr or result.stdout)[:300]}"
        )
    return result.stdout


def normalize_component(application_id: str, activity_name: str) -> str:
    if activity_name.startswith("."):
        activity_name = application_id + activity_name
    elif "." not in activity_name:
        activity_name = f"{application_id}.{activity_name}"
    return f"{application_id}/{activity_name}"


def parse_apk_contract(badging: str, xmltree: str) -> ApkContract:
    package_match = re.search(r"^package: name='([^']+)'", badging, re.MULTILINE)
    launcher_match = re.search(r"^launchable-activity: name='([^']+)'", badging, re.MULTILINE)
    if package_match is None or launcher_match is None:
        raise ContractError("APK badging omitted package or launchable activity")
    application_id = package_match.group(1)
    activities = re.findall(
        r'android:name\([^)]*\)="([^"]+)"(?: \(Raw: "[^"]+"\))?',
        xmltree,
    )
    snapshots = [name for name in activities if name.endswith(".ui.UiSnapshotActivity")]
    if len(snapshots) != 1:
        raise ContractError(
            f"debug APK must expose exactly one UiSnapshotActivity; found {snapshots}"
        )
    return ApkContract(
        application_id=application_id,
        launcher_component=normalize_component(application_id, launcher_match.group(1)),
        snapshot_component=normalize_component(application_id, snapshots[0]),
    )


def inspect_apk_contract(
    apk: Path,
    *,
    run_text: Callable[[Sequence[str]], str] = _run_text,
    aapt: str | None = None,
    aapt2: str | None = None,
) -> ApkContract:
    """Read identity from the same APK bytes whose SHA is attested."""
    if not apk.is_file():
        raise ContractError(f"APK does not exist: {apk}")
    badging = run_text([aapt or find_build_tool("aapt"), "dump", "badging", str(apk)])
    xmltree = run_text(
        [
            aapt2 or find_build_tool("aapt2"),
            "dump",
            "xmltree",
            "--file",
            "AndroidManifest.xml",
            str(apk),
        ]
    )
    return parse_apk_contract(badging, xmltree)


def production_capture_subdir(repo_root: Path) -> str:
    source = (
        repo_root
        / "app/src/main/kotlin/me/hletrd/telecampro/storage/MediaStoreWriter.kt"
    ).read_text(encoding="utf-8")
    matches = re.findall(r'^\s*const val CAPTURE_SUBDIR\s*=\s*"([^"]+)"', source, re.MULTILINE)
    if len(matches) != 1:
        raise ContractError(f"expected one production CAPTURE_SUBDIR, found {matches}")
    return matches[0]


def harness_source_manifest(harness_root: Path) -> list[dict[str, object]]:
    """Hash every versionable harness input, excluding only generated artifacts/caches."""
    entries: list[dict[str, object]] = []
    for path in sorted(harness_root.rglob("*")):
        relative = path.relative_to(harness_root)
        if any(part in {"reports", "__pycache__", ".pytest_cache"} for part in relative.parts):
            continue
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            raise ContractError(f"harness source must not be a symlink: {relative.as_posix()}")
        if stat.S_ISDIR(mode):
            continue
        if not stat.S_ISREG(mode):
            raise ContractError(f"harness source must be a regular file: {relative.as_posix()}")
        payload = path.read_bytes()
        entries.append(
            {
                "path": relative.as_posix(),
                "bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest(),
            }
        )
    if not entries:
        raise ContractError(f"no harness sources found under {harness_root}")
    return entries


def source_manifest_sha256(entries: list[dict[str, object]]) -> str:
    canonical = "".join(
        f"{entry['sha256']}  {entry['bytes']}  {entry['path']}\n" for entry in entries
    ).encode()
    return hashlib.sha256(canonical).hexdigest()
